name: StorageWipe
version: 2.2
description: This plugin helps you empty Barrels, Chests, BlastFurnaces, Dispensers, Droppers, Furnaces, Hoppers from your chunk / world / server.
authors: [aantonschouten, SirDankenstein]
website: https://www.spigotmc.org/resources/storagewipe.93195/

main: me.StorageWipe.Main
database: false

commands:
  storagewipe:
    description: Empty various storage blocks from your chunk / world / server.
    permission: storagewipe.cmd